
/* Autogenerated. Do not edit. */

import Foundation
import Alamofire
/// The client for the API. Call routes using the namespaces inside this object.
open class DropboxClient : BabelClient {
	let accessToken : DropboxAccessToken
	static var version = "2.0.3"

	/// Shared instance for convenience
	open static var sharedClient : DropboxClient!

	open override func additionalHeaders(_ noauth : Bool) -> [String: String] {
		var headers = ["User-Agent": "OfficialDropboxSwiftSDKv2/\(DropboxClient.version)"]
		if (!noauth) {
			headers["Authorization"] = "Bearer \(self.accessToken)"
		}
		return headers
	}

	public convenience init(accessToken: DropboxAccessToken) {
		let manager = Manager(serverTrustPolicyManager: DropboxServerTrustPolicyManager())
        manager.startRequestsImmediately = false
		self.init(accessToken: accessToken,
				  manager: manager,
				  baseHosts: [
		              "meta"    : "https://api.dropbox.com/2",
		              "content" : "https://api-content.dropbox.com/2",
		              "notify"  : "https://notify.dropboxapi.com/2"
		          ])
	}
    /// Routes within the files namespace. See FilesRoutes for details.
    open var files : FilesRoutes!
    /// Routes within the sharing namespace. See SharingRoutes for details.
    open var sharing : SharingRoutes!
    /// Routes within the users namespace. See UsersRoutes for details.
    open var users : UsersRoutes!
    public init(accessToken: DropboxAccessToken, manager: Manager, baseHosts: [String : String]) {
        self.accessToken = accessToken
        super.init(manager: manager, baseHosts: baseHosts)
        self.files = FilesRoutes(client: self)
        self.sharing = SharingRoutes(client: self)
        self.users = UsersRoutes(client: self)
    }
}
